/* Seeds the database from seed-data.json (generated by Naratake)
   plus a default admin account. Run via `npm run setup`.

   This file is only the runner: every module's seeding lives in
   prisma/seeds/<module>.ts. Naratake regenerates the REGISTRY block
   below with just the modules a site enabled, so a disabled module's seed code
   never ships and the wipe never names a model that left the schema. */

import { PrismaClient } from '@prisma/client';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import type { SeedData, SeedStep } from './seeds/types';

/* ── REGISTRY ─────────────────────────────────────────────── */
import { seed as settings } from './seeds/settings';
import { seed as auth, seededAdminPassword } from './seeds/auth';
import { seed as media } from './seeds/media';
import { seed as catalog } from './seeds/catalog';
import { seed as customers } from './seeds/customers';
import { seed as promotions } from './seeds/promotions';
import { seed as payments } from './seeds/payments';
import { seed as orders } from './seeds/orders';

/* dependency order: a step may read only what an EARLIER step created.
   The dev wipe runs it backwards. */
const STEPS: SeedStep[] = [settings, auth, media, catalog, customers, promotions, payments, orders];
/* ── END REGISTRY ─────────────────────────────────────── */

const prisma = new PrismaClient();

async function main() {
  const data = JSON.parse(readFileSync(join(__dirname, 'seed-data.json'), 'utf-8')) as SeedData;

  // production (SEED_IF_EMPTY=1): each entity GROUP seeds only when its own
  // table is empty — a live site that enables bookings/classes later gets that
  // module's seed on redeploy while orders/customers/menu edits stay untouched.
  // dev: wipe and reseed everything for a clean slate.
  const prod = process.env.SEED_IF_EMPTY === '1';
  if (!prod) {
    await prisma.$transaction([...STEPS].reverse().flatMap((step) => step.wipe(prisma)));
  }
  // on prod, a count() FAILURE must NOT be read as "empty" — that would re-seed a
  // live table on any transient DB hiccup. Fail closed: treat an error as non-empty.
  const empty = async (count: () => Promise<number>) => {
    if (!prod) return true;
    try { return (await count()) === 0; } catch { return false; }
  };

  for (const step of STEPS) await step.run(prisma, data, empty);

  console.log('──────────────────────────────────────────────');
  console.log('  Database seeded.');
  console.log(`  Admin login:  ${data.adminEmail}`);
  console.log(`  Password:     ${seededAdminPassword()}`);
  console.log('  → change it after first login (Admin → Settings)');
  console.log('──────────────────────────────────────────────');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
