/* GENERATED by LocalSite Studio — the modules installed on this site.
   Imported for side effects only: each one registers what it owes when an order
   is voided (lib/hooks.ts). A module that is not listed here is not on this
   site, and its tables do not exist. */

import './modules/catalog.hooks';
import './modules/orders.hooks';
import './modules/payments.hooks';
import './modules/customers.hooks';
import './modules/promotions.hooks';
