/* Typed access to site.config.json (generated by Naratake). */

import config from '@/site.config.json';

/** One field of a user-defined collection (mirrors CollectionField in schema). */
export interface SiteCollectionField {
  key: string;
  label: string;
  labelZh: string;
  kind:
    | 'text'
    | 'textarea'
    | 'richtext'
    | 'number'
    | 'money'
    | 'boolean'
    | 'date'
    | 'select'
    | 'image'
    | 'gallery'
    | 'url'
    | 'email'
    // edges: the value stored in `data` is the target entry's slug (one, or an
    // array of them), which is why a content model still needs no migration
    | 'reference'
    | 'references';
  required?: boolean;
  options?: string[];
  /** reference/references only: the collection slug this field points at */
  refCollection?: string;
  /** how a reader meets this field; see fieldRoles below */
  role?: FieldRole;
  help?: string;
  helpZh?: string;
}

/** What a field IS to a reader, as opposed to what it stores. Mirrors FieldRole
    in schema. Without this a page prints the admin form's own labels — "Byline:
    Maria Alvarez", "Story" above the article body — which is the loudest signal
    that a page was generated rather than designed. */
export type FieldRole =
  | 'field' // labelled value, the way every field renders by default
  | 'cover' // the lead image, shown full width above the title
  | 'standfirst' // the sentence under the headline, set larger than body
  | 'byline' // credited, not labelled: "By Maria Alvarez"
  | 'body' // long form, no label, the widest measure on the page
  | 'chip' // a compact tag row, for categories and the like
  | 'meta' // small print beside the byline: date, reading time, source
  | 'flag' // a boolean worth shouting: BREAKING, LIVE, SPONSORED
  | 'hidden'; // stored and editable, never shown to a reader

/** A content type defined in the editor. Entries live in CollectionEntry rows;
    this definition tells the site and the admin how to read and render them,
    with no database round trip. */
export interface SiteCollection {
  slug: string;
  name: string;
  nameZh: string;
  singular: string;
  singularZh: string;
  fields: SiteCollectionField[];
  titleField: string;
  detailPage?: boolean;
  sort?: 'manual' | 'newest' | 'title';
}

/** How a reader meets each field. Verbatim twin of `fieldRoles` in schema — a
    declared role wins, and everything else is inferred exactly the way the
    renderers guessed before roles existed, so an untouched content type renders
    unchanged. The title is the page's h1 no matter what anyone declares. */
export function fieldRoles(col: SiteCollection): Map<string, FieldRole> {
  const declared = col.fields.find((f) => f.role === 'cover');
  const cover = declared ?? col.fields.find((f) => f.kind === 'image');
  const out = new Map<string, FieldRole>();
  for (const f of col.fields) {
    out.set(f.key, f.key === col.titleField ? 'hidden' : (f.role ?? (f === cover ? 'cover' : 'field')));
  }
  return out;
}

export interface SiteConfig {
  name: string;
  slug: string;
  business: {
    name: string;
    phone: string;
    email: string;
    address: { line1: string; city: string; state: string; zip: string };
    timezone: string;
    taxRateBp: number;
    hours: Record<string, [string, string][] | null>;
    socials?: Record<string, string>;
    logo?: string;
    /** intrinsic pixel size captured at upload — lets the nav reserve the true box (CLS) */
    logoDims?: { w: number; h: number };
    /** regulated trades publish a licence; printed in the footer legal strip */
    license?: { number: string; authority?: string };
    /** schema.org type for the JSON-LD block (RealEstateAgent, LegalService…) */
    schemaType?: string;
  };
  /** 頁尾是否帶「用 Naratake 製作」。只有雲端發佈的站是 true。 */
  attribution?: boolean;
  bilingual: boolean;
  secondaryLocale?: 'zh' | 'es' | null;
  enabledModules: string[];
  pages: { name: string; slug: string; hideFromNav?: boolean; hideFromFooter?: boolean }[];
  /** page hosting the OrderingWidget checkout — target for cart pill/button */
  orderPath?: string;
  /** privacy / terms / trade disclosures, assembled at export time from the
      modules this site actually runs — see packages/codegen/src/legal.ts */
  legalDocs?: {
    slug: string;
    title: string;
    titleZh: string;
    sections: { h: string; hZh: string; body: string[]; bodyZh: string[] }[];
  }[];
  fonts: { heading: string; body: string };
  /** which chrome the generic collection routes should wear */
  chrome?: 'masthead' | 'navbar';
  /** the masthead the merchant arranged, so a story page wears the same one */
  masthead?: {
    seal: string;
    actionLabel: string;
    actionLabelZh: string;
    actionHref: string;
    dateline?: string;
    datelineZh?: string;
    /** the paper's desks, so a story page keeps the section deck the front page has */
    sectionLinks?: { label: string; href: string }[];
  } | null;
  /** the navbar's second deck + logo box, so a generic entry page keeps the site's own nav */
  nav?: { sectionLinks?: { label: string; href: string }[]; logoSize?: 'sm' | 'md' | 'lg' } | null;
  brand?: { primary: string; primaryFg: string; accent: string; secondary: string };
  analytics?: {
    ga4Id?: string | null;
    metaPixelId?: string | null;
    gtmId?: string | null;
    customHeadHtml?: string | null;
  };
  seo?: { ratingValue: number; ratingCount: number } | null;
  /** user-defined content types (jobs, courses, case studies…) */
  collections?: SiteCollection[];
  /** derived from the components actually placed on the site */
  features?: { listings?: boolean };
}

export const site = config as unknown as SiteConfig;

/** Collection definition by slug — the one gate every collection route uses,
    so an unknown slug 404s instead of querying the database. */
export function siteCollection(slug: string): SiteCollection | undefined {
  return (site.collections ?? []).find((c) => c.slug === slug);
}

/** One printable address line. A merchant who publishes a city but no street —
    a broker, a mobile trade, anyone working by appointment — had the empty
    line1 glued in anyway, so the footer read ", Plano, TX 75075". Join the
    parts that exist; never punctuate an absence. */
export function addressLine(a: { line1?: string; city?: string; state?: string; zip?: string }): string {
  const region = [a.state, a.zip].filter(Boolean).join(" ").trim();
  return [a.line1, a.city, region].map((s) => (s ?? "").trim()).filter(Boolean).join(", ");
}

/* What to hand Google's geocoder. Two rules, both measured against the live
   keyless embed rather than assumed:

   1. NEVER the business name. A name turns the lookup into a place search, and
      a merchant with no Google listing yet — which is every new merchant — gets
      whatever Google guesses. "Phoenix Legacy Realty, 6301 Preston Rd, Plano,
      TX 75024" pinned a church in Dallas; the identical address without the
      name pinned the building. The address IS the place; the name only helps a
      business Google already knows, and it silently ruins the rest.
   2. The ZIP only rides along when there is a street to anchor it. With no
      street, "Plano, TX 75075" — and even a bare "75075" — collapses the embed
      to a zoomed-out map of the planet, while "Plano, TX" lands on Plano.

   '' when there is nothing to place: the caller then draws no map, because a
   map of the wrong place is worse than no map. */
export function mapQueryFor(a: { line1?: string; city?: string; state?: string; zip?: string }): string {
  const parts = (a.line1 ?? "").trim()
    ? [a.line1, a.city, [a.state, a.zip].filter(Boolean).join(" ")]
    : [a.city, a.state];
  return parts.map((s) => (s ?? "").trim()).filter(Boolean).join(", ");
}
