/* GENERATED by LocalSite Studio — the back-office routes this site mounts.

   server/admin.ts mounts this list AFTER its session middleware, so every route
   named here is behind the session gate. Nothing here may run before it. */

import type { Hono } from 'hono';

import { routes as auth } from './auth.admin';
import { routes as catalog } from './catalog.admin';
import { routes as customers } from './customers.admin';
import { routes as media } from './media.admin';
import { routes as orders } from './orders.admin';
import { routes as promotions } from './promotions.admin';
import { routes as settings } from './settings.admin';
import { routes as stats } from './stats.admin';

export const ADMIN_MODULE_ROUTES: Hono[] = [auth, catalog, customers, media, orders, promotions, settings, stats];
